---
volumes:
  data:
  extensions:

services:
  freshrss:
    image: freshrss/freshrss:1.26.3
    container_name: freshrss
    restart: unless-stopped
    logging:
      options:
        max-size: 10m
    volumes:
      - data:/var/www/FreshRSS/data
      - extensions:/var/www/FreshRSS/extensions
    ports:
      - 13842:80
    environment:
      TZ: America/New_York
      CRON_MIN: '2,32'
