---
version: "2.4"
services:
  freshrss:
    image: lscr.io/linuxserver/freshrss:1.24.0
    container_name: freshrss
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - data:/config
    ports:
      - 13842:80
    restart: unless-stopped
volumes:
  data:
